'use client';

import { useEffect, useState } from 'react';

const ArrowUpRight = ({ size = 16 }: { size?: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M7 17 17 7" /><path d="M7 7h10v10" /></svg>
);
const Check = () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m5 12 4 4L19 6" /></svg>;
const workflows = [
  ['01', '想法完善', '把一个模糊想法，打磨成值得验证的产品机会。'],
  ['02', '竞品分析', '从市场、用户到商业模式，建立完整的竞争情报。'],
  ['03', 'PRD 交付', '将战略上下文转换为工程团队可以直接执行的 PRD。'],
  ['04', '需求排布', '用 RICE、Kano 等框架，在资源有限时做出更好取舍。'],
];

export default function HomePage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [user, setUser] = useState<{ email: string } | null>(null);
  const [registerOpen, setRegisterOpen] = useState(false);
  const [registerEmail, setRegisterEmail] = useState('');
  const [registerPassword, setRegisterPassword] = useState('');
  const [registerCode, setRegisterCode] = useState('');
  const [registerMessage, setRegisterMessage] = useState('');
  const [registerBusy, setRegisterBusy] = useState(false);
  const [loginOpen, setLoginOpen] = useState(false);
  const [accountOpen, setAccountOpen] = useState(false);
  const [loginEmail, setLoginEmail] = useState(''); const [loginPassword, setLoginPassword] = useState(''); const [loginMessage, setLoginMessage] = useState(''); const [loginBusy, setLoginBusy] = useState(false);
  useEffect(() => { fetch('/api/auth/me').then(r => r.ok ? r.json() : null).then(data => setUser(data?.user || null)).catch(() => {}); }, []);
  async function handleRegister(e: React.FormEvent) {
    e.preventDefault(); setRegisterBusy(true); setRegisterMessage('');
    try {
      const payload = { email: registerEmail, password: registerPassword, ...(registerCode ? { code: registerCode } : {}) };
      const res = await fetch('/api/auth/register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) });
      const data = await res.json(); if (!res.ok) throw new Error(data.error); if (!registerCode) { setRegisterMessage('验证码已发送，请查收邮箱'); } else { setUser(data.user); setRegisterOpen(false); setRegisterMessage(''); }
    } catch (err: any) { setRegisterMessage(err.message || '注册失败'); } finally { setRegisterBusy(false); }
  }
  async function handleLogin(e: React.FormEvent) { e.preventDefault(); setLoginBusy(true); setLoginMessage(''); try { const res = await fetch('/api/auth/login', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ email:loginEmail, password:loginPassword }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setUser(data.user); setLoginOpen(false); } catch (err:any) { setLoginMessage(err.message || '登录失败'); } finally { setLoginBusy(false); } }
  async function handleLogout() { await fetch('/api/auth/logout', { method:'POST' }).catch(() => {}); setUser(null); setAccountOpen(false); }
  return (
    <main className="landing-page">
      <nav className="landing-nav" aria-label="主导航">
        <a className="brand-mark" href="/" aria-label="PM Workbench 首页"><span className="brand-dot" /><span>PM <em>Workbench</em></span></a>
        <button className="mobile-menu" aria-label="打开菜单" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><span /><span /></button>
        <div className={`nav-links ${menuOpen ? 'is-open' : ''}`}>
          <a href="#capabilities" onClick={() => setMenuOpen(false)}>产品能力</a><a href="#workflows" onClick={() => setMenuOpen(false)}>工作流</a><a href="#method" onClick={() => setMenuOpen(false)}>方法论</a>{user ? <><a className="nav-login nav-workbench-link" href="/chat">进入工作台 <ArrowUpRight size={14} /></a><div className="nav-account-wrap"><button className="nav-user-avatar" title={user.email} aria-label="打开账号菜单" onClick={() => setAccountOpen(!accountOpen)}>{user.email.charAt(0).toUpperCase()}</button>{accountOpen && <div className="nav-account-menu"><strong>{user.email}</strong><a href="/account/password">修改密码</a><button onClick={handleLogout}>退出账号</button><button onClick={() => { setAccountOpen(false); setLoginOpen(true); }}>切换账号</button></div>}</div></> : <><button className="nav-login nav-login-quiet" onClick={() => { setLoginOpen(true); setMenuOpen(false); }}>登录</button><button className="nav-login nav-register-button" onClick={() => { setRegisterOpen(true); setMenuOpen(false); }}>注册 <ArrowUpRight size={14} /></button></>}
        </div>
      </nav>

      <section className="hero-section">
        <div className="hero-copy"><div className="eyebrow"><span className="eyebrow-pulse" /> AI 原生的产品工作方式</div><h1><span className="hero-line">把模糊的产品问题，</span><span className="hero-line hero-accent">变成下一步行动。</span></h1><p className="hero-lede">PM Workbench 把想法、竞品、战略、PRD、发布与复盘，编排成一组可以直接使用的 AI 工作流；还可以帮你审查、改写和完善已有内容。</p><div className="hero-actions"><a className="button button-primary" href="/workflow">探索工作流 <ArrowUpRight /></a><a className="button button-secondary" href="#method">看看它如何工作 <span className="button-arrow">↓</span></a></div><div className="hero-note"><Check /> 10 个结构化工作流&nbsp;&nbsp;·&nbsp;&nbsp;AI 审查修改&nbsp;&nbsp;·&nbsp;&nbsp;支持 OpenAI 兼容模型</div></div>
        <div className="hero-product" aria-label="PM Workbench 产品预览"><div className="product-window-bar"><div className="window-dots"><i /><i /><i /></div><span>pm-workbench / new-session</span><b>⌘ K</b></div><div className="product-body"><div className="product-sidebar"><strong>PM<span>W</span></strong><div className="side-line active" /><div className="side-line" /><div className="side-line short" /><div className="side-bottom" /></div><div className="product-main"><div className="product-kicker">NEW SESSION <span>·</span> IDEA REFINEMENT</div><h3>让我们把这个想法<br />变成一个可验证的机会。</h3><div className="chat-card user-card">我想做一个帮助独立创作者管理赞助合作的工具。</div><div className="chat-card ai-card"><span className="ai-avatar">✦</span><div><strong>先从问题开始</strong><p>谁正在被什么问题卡住？我们先把用户、场景和未满足的需求说清楚。</p><div className="ai-chips"><span>用户是谁？</span><span>当前替代方案</span></div></div></div><div className="product-input"><span>继续描述你的产品问题…</span><b><ArrowUpRight size={14} /></b></div></div></div><div className="floating-badge badge-top"><span>✦</span> AI 正在编排</div><div className="floating-badge badge-bottom"><span>10</span> workflows ready</div></div>
      </section>

      <section className="logo-strip" aria-label="产品能力标签"><span>为产品团队而生</span><i /><strong>战略</strong><strong>探索</strong><strong>交付</strong><strong>增长</strong><strong>AI 运营</strong></section>
      <section className="statement-section" id="method"><div className="statement-copy-wrap"><p className="section-label">产品工作的真正瓶颈</p><h2>好产品不是从“写一个 PRD”开始的。<br /><span>它从提出正确的问题开始。</span></h2><p className="statement-copy">真正耗时的，从来不是文档排版，而是在不确定中找到方向。Workbench 把那些隐形的思考步骤显性化，让每一次对话都能沉淀为可复用的决策。</p></div><div className="method-visual" aria-label="从问题到决策的工作方式图例"><div className="method-caption">WORKBENCH METHOD <span>01—03</span></div><div className="method-node node-question"><small>01 · 提问</small><strong>我们真正要解决的<br />问题是什么？</strong></div><div className="method-connector"><i /><i /><i /></div><div className="method-node node-evidence"><small>02 · 取证</small><strong>用户、市场与<br />现有数据</strong></div><div className="method-connector"><i /><i /><i /></div><div className="method-node node-decision"><small>03 · 决策</small><strong>下一步最小<br />可验证行动</strong></div></div></section>

      <section className="capabilities-section" id="capabilities"><div className="section-heading"><div><p className="section-label">一个工作台，多种工作模式</p><h2>从洞察到交付，<br />每一步都有结构。</h2></div><a href="/workflow" className="text-link">查看全部能力 <ArrowUpRight size={15} /></a></div><div className="capability-grid"><article className="capability-card card-blue"><span className="card-index">01 / 想清楚</span><h3>先把问题想清楚</h3><p>用 JTBD、用户旅程和问题框架，把“感觉应该做”变成可验证的机会假设。</p><div className="ui-shot shot-blue"><div className="shot-toolbar"><i /><i /><span>机会假设画布</span></div><div className="shot-columns"><div><small>用户任务</small><b>找到更快的替代方案</b></div><div><small>核心问题</small><b>决策信息太分散</b></div></div><div className="shot-progress"><span style={{ width:'72%' }} /></div></div></article><article className="capability-card card-dark"><span className="card-index">02 / 做决策</span><h3>让取舍更有依据</h3><p>把竞品、市场、商业模型和风险放进同一张决策桌，快速看到真正重要的变量。</p><div className="ui-shot shot-dark"><div className="shot-toolbar"><i /><i /><span>优先级矩阵</span></div><div className="matrix"><span className="dot dot-a" /><span className="dot dot-b" /><span className="dot dot-c" /><span className="dot dot-d" /></div><div className="shot-axis"><span>影响力</span><span>投入成本</span></div></div></article><article className="capability-card card-lilac"><span className="card-index">03 / 交付</span><h3>交付可以从容一点</h3><p>从战略上下文到用户故事、验收标准和路线图，一次对话生成工程就绪的交付物。</p><div className="ui-shot shot-lilac"><div className="shot-toolbar"><i /><i /><span>工程就绪 PRD</span></div><div className="shot-check"><span><Check /> 用户故事</span><span><Check /> 验收标准</span><span><Check /> 成功指标</span></div></div></article></div><div className="review-highlight"><div><span className="card-index">04 / 审查与修改</span><h3>已有内容，也能继续变好。</h3><p>把 PRD、需求说明、发布文案或研究结论交给 AI 审查：找出逻辑漏洞、信息缺口和表达问题，并给出可直接采纳的修改建议。</p></div><div className="review-shot"><div className="review-toolbar"><span>PRD · 首页改版</span><b>审查完成</b></div><div className="review-row"><span className="review-mark">!</span><div><strong>目标用户描述不够具体</strong><p>建议补充使用场景、频率与当前替代方案。</p></div><em>建议修改</em></div><div className="review-row"><span className="review-mark ok">✓</span><div><strong>成功指标与目标一致</strong><p>留存率、激活率已形成完整指标链路。</p></div><em className="ok-text">已通过</em></div></div></div></section>

      <section className="workflow-section" id="workflows"><div className="workflow-intro"><p className="section-label">THE WORKFLOW LIBRARY</p><h2>不是一个聊天框。<br /><span>是一套产品操作系统。</span></h2><p>每一条工作流都由多个专业 Skill 协作完成，沿着清晰的阶段推进，并在关键节点留下可以继续使用的产出物。</p><a className="button button-primary" href="/workflow">浏览 10 个工作流 <ArrowUpRight /></a></div><div className="workflow-list">{workflows.map(([num, title, desc]) => <a href="/workflow" className="workflow-row" key={num}><span className="workflow-num">{num}</span><div><h3>{title}</h3><p>{desc}</p></div><ArrowUpRight size={19} /></a>)}</div></section>
      <section className="cta-section"><div className="cta-stamp">PM<br />W</div><p className="section-label">READY WHEN YOU ARE</p><h2>下一次产品讨论，<br /><span>从一个更好的问题开始。</span></h2><p>打开 Workbench，选择一个工作流，或者直接告诉它你正在面对什么。</p><a className="button button-dark" href="/chat">进入 PM Workbench <ArrowUpRight /></a></section>
      <footer className="landing-footer"><span>© 2025 子修 · PM Workbench</span><span>为好奇的产品人而造。</span><a href="/settings">模型设置 <ArrowUpRight size={13} /></a></footer>
      {loginOpen && <div className="register-modal-backdrop" role="presentation"><section className="register-modal" role="dialog" aria-modal="true" aria-labelledby="login-title"><button className="register-modal-close" aria-label="关闭登录弹窗" onClick={() => setLoginOpen(false)}>×</button><p className="section-label">WELCOME BACK</p><h2 id="login-title">登录工作台</h2><p className="register-modal-lede">继续你的工作流、对话和产品产出。</p><form onSubmit={handleLogin} className="register-form"><label>邮箱<input className="input" type="email" required value={loginEmail} onChange={e => setLoginEmail(e.target.value)} placeholder="name@qq.com" /></label><label>密码<input className="input" type="password" required value={loginPassword} onChange={e => setLoginPassword(e.target.value)} placeholder="请输入密码" /></label>{loginMessage && <div className="register-message">{loginMessage}</div>}<button className="button button-primary register-submit" disabled={loginBusy}>{loginBusy ? '登录中…' : '登录'}</button></form><p className="register-modal-foot">还没有账号？<button className="modal-inline-link" onClick={() => { setLoginOpen(false); setRegisterOpen(true); }}>立即注册</button></p></section></div>}
      {registerOpen && <div className="register-modal-backdrop" role="presentation"><section className="register-modal" role="dialog" aria-modal="true" aria-labelledby="register-title"><button className="register-modal-close" aria-label="关闭注册弹窗" onClick={() => setRegisterOpen(false)}>×</button><p className="section-label">JOIN PM WORKBENCH</p><h2 id="register-title">创建你的账号</h2><p className="register-modal-lede">用邮箱注册，保存你的工作流、对话和产品产出。</p><form onSubmit={handleRegister} className="register-form"><label>邮箱<input className="input" type="email" required value={registerEmail} onChange={e => setRegisterEmail(e.target.value)} placeholder="name@qq.com" /></label><label>密码<input className="input" type="password" required minLength={8} value={registerPassword} onChange={e => setRegisterPassword(e.target.value)} placeholder="至少 8 位" /></label><label>邮箱验证码<input className="input" inputMode="numeric" value={registerCode} onChange={e => setRegisterCode(e.target.value)} placeholder="先发送验证码" /></label>{registerMessage && <div className={`register-message ${registerMessage.includes('发送') ? 'is-success' : ''}`}>{registerMessage}</div>}<button className="button button-primary register-submit" disabled={registerBusy}>{registerBusy ? '处理中…' : registerCode ? '完成注册' : '发送验证码'}</button></form><p className="register-modal-foot">已有账号？<button className="modal-inline-link" onClick={() => { setRegisterOpen(false); setLoginOpen(true); }}>去登录</button></p></section></div>}
    </main>
  );
}
