'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
const icons=['◈','◌','◇','▦'];
const actions=['','login','logout','register','llm_response','update_user','delete_user','create_session','delete_session','rename_session','create_output','update_output','delete_output','create_output_version','update_output_version','delete_folder','upload_file','delete_file'];
type Section='overview'|'users'|'audit';
export default function AdminPage(){
 const [section,setSection]=useState<Section>('overview'),[data,setData]=useState<any>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[edit,setEdit]=useState<any>(null),[logPage,setLogPage]=useState(1),[logAction,setLogAction]=useState('');
 const load=async(page=logPage,action=logAction)=>{try{const r=await fetch('/api/admin/users?page='+page+'&pageSize=15'+(action?'&action='+encodeURIComponent(action):''));const d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}catch(e:any){setError(e.message)}};
 useEffect(()=>{load(1,logAction)},[logAction]);
 const users=useMemo(()=>data?.users?.filter((u:any)=>u.email.toLowerCase().includes(query.toLowerCase()))||[],[data,query]), logs=data?.logs?.items||[],meta=data?.logs||{};
 async function save(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/admin/users',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...edit,password:edit.password||undefined})});if(!r.ok){setError((await r.json()).error);return}setEdit(null);load()}
 const nav=(s:Section,label:string)=><button className={section===s?'active':''} onClick={()=>setSection(s)}>{label}</button>;
 return <main className="admin-page"><aside className="admin-sidebar"><Link href="/" className="admin-brand"><span>PM</span> Workbench</Link><nav className="admin-nav">{nav('overview','总览')}{nav('users','账号管理')}{nav('audit','审计日志')}</nav><div className="admin-sidebar-foot">安全控制台<br/><small>子修 · PM Workbench</small></div></aside><section className="admin-content"><header className="admin-topbar"><div><p>ADMIN CONSOLE / {section.toUpperCase()}</p><h1>{section==='overview'?'运营总览':section==='users'?'账号管理':'审计日志'}</h1></div><Link href="/chat" className="admin-back">返回工作台 →</Link></header>{error&&<div className="admin-error">{error}</div>}
 {section==='overview'&&<><div className="admin-metrics">{[['注册账号',data?.stats?.users||0],['活跃会话',data?.stats?.sessions||0],['产出物',data?.stats?.outputs||0],['文件夹',data?.stats?.folders||0]].map(([k,v],i)=><div className="admin-metric" key={String(k)}><span>{icons[i]}</span><small>{k}</small><strong>{String(v)}</strong><em>实时数据</em></div>)}</div><div className="admin-overview-grid"><section className="admin-panel admin-summary"><div className="admin-panel-head"><div><p className="admin-kicker">OPERATIONS SNAPSHOT</p><h2>今天的运营重点</h2></div></div><div className="admin-summary-body"><div><strong>{data?.stats?.users||0}</strong><span>注册账号</span></div><div><strong>{data?.stats?.sessions||0}</strong><span>活跃会话</span></div><div><strong>{data?.stats?.outputs||0}</strong><span>产出物</span></div></div></section><section className="admin-panel admin-summary"><div className="admin-panel-head"><div><p className="admin-kicker">QUICK ACCESS</p><h2>管理入口</h2></div></div><div className="admin-quick-actions"><button onClick={()=>setSection('users')}>管理账号 <span>→</span></button><button onClick={()=>setSection('audit')}>查看审计日志 <span>→</span></button></div></section></div></>}
 {section==='users'&&<section className="admin-panel" id="users"><div className="admin-panel-head"><div><p className="admin-kicker">ACCOUNT DIRECTORY</p><h2>账号目录</h2></div><div className="admin-toolbar"><input placeholder="搜索邮箱" value={query} onChange={e=>setQuery(e.target.value)}/><span>{users.length} 个账号</span></div></div><div className="admin-table-head"><span>账号</span><span>角色</span><span>状态</span><span>注册时间</span><span></span></div>{users.map((u:any)=><div className="admin-table-row" key={u.userId}><div className="admin-user-cell"><b>{u.email.charAt(0).toUpperCase()}</b><strong>{u.email}</strong></div><span className={u.role==='admin'?'role-admin':'role-user'}>{u.role==='admin'?'管理员':'普通用户'}</span><span className={u.active?'status-on':'status-off'}><i/>{u.active?'正常':'已禁用'}</span><span className="admin-muted">{u.createdAt.slice(0,10)}</span><button className="admin-edit" onClick={()=>setEdit({...u,password:''})}>编辑</button></div>)}{!users.length&&<div className="admin-empty">暂无匹配账号</div>}</section>}
 {section==='audit'&&<section className="admin-panel" id="audit"><div className="admin-panel-head"><div><p className="admin-kicker">AUDIT TRAIL</p><h2>操作审计日志</h2></div><div className="admin-toolbar"><select value={logAction} onChange={e=>{setLogAction(e.target.value);setLogPage(1)}}><option value="">全部操作</option>{actions.slice(1).map(a=><option key={a}>{a}</option>)}</select><button className="admin-export" onClick={()=>{const blob=new Blob([JSON.stringify(logs,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='audit-logs.json';a.click()}}>导出当前页 ↓</button></div></div>{logs.map((l:any)=><div className="audit-row" key={l.id}><span className="audit-dot"/><div><strong>{l.action}</strong><small>{l.email||'系统'} · {String(l.createdAt).replace('T',' ').slice(0,19)}</small></div><em>{l.detail}</em></div>)}{!logs.length&&<div className="admin-empty">暂无匹配日志</div>}<div className="admin-pagination"><button disabled={logPage<=1} onClick={()=>{setLogPage(p=>p-1);load(logPage-1,logAction)}}>上一页</button><span>第 {meta.page||1} / {meta.totalPages||1} 页 · 共 {meta.total||0} 条</span><button disabled={logPage>=(meta.totalPages||1)} onClick={()=>{setLogPage(p=>p+1);load(logPage+1,logAction)}}>下一页</button></div></section>}
 {edit&&<div className="admin-modal-backdrop" onClick={()=>setEdit(null)}><form className="admin-edit-modal" onClick={e=>e.stopPropagation()} onSubmit={save}><button type="button" className="admin-close" onClick={()=>setEdit(null)}>×</button><p className="admin-kicker">EDIT ACCOUNT</p><h2>编辑账号</h2><label>邮箱<input value={edit.email} onChange={e=>setEdit({...edit,email:e.target.value})}/></label><label>新密码<input type="password" placeholder="留空表示不修改" value={edit.password} onChange={e=>setEdit({...edit,password:e.target.value})}/></label><label>角色<select value={edit.role} onChange={e=>setEdit({...edit,role:e.target.value})}><option value="user">普通用户</option><option value="admin">管理员</option></select></label><label>状态<select value={edit.active?'1':'0'} onChange={e=>setEdit({...edit,active:e.target.value==='1'})}><option value="1">启用</option><option value="0">禁用</option></select></label><button className="admin-save">保存修改</button></form></div>}</section></main>
}
